[target.'cfg(target_os="macos")']
# Postgres symbols won't be available until the extension is loaded at runtime,
# so allow undefined symbols at link time on macOS.
rustflags = ["-Clink-arg=-Wl,-undefined,dynamic_lookup"]
