//! The declarative description of a GraphQL source.
//!
//! A [`GraphQlSpec`] fully describes a GraphQL API: its single `endpoint`, how
//! to authenticate, and a list of [`GraphQlTable`]s. Each table carries a stored
//! GraphQL **document** (with variables) plus where its rows live in the
//! response. The [`GraphQlConnector`](crate::GraphQlConnector) reads *any* spec
//! and implements the `Connector` trait — so a hand-written spec and a spec
//! generated by introspection run through the exact same engine. Everything
//! derives `serde`, so specs load from JSON or come out of the generator.

use connector_sdk::DataType;
use serde::{Deserialize, Serialize};

/// A complete description of one GraphQL API source.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct GraphQlSpec {
    /// Short identifier for this source, e.g. `"countries"`.
    pub name: String,
    /// The single GraphQL endpoint, POSTed to, e.g. `"https://api.github.com/graphql"`.
    pub endpoint: String,
    /// How to authenticate requests.
    #[serde(default)]
    pub auth: AuthSpec,
    /// The tables this source exposes.
    pub tables: Vec<GraphQlTable>,
}

impl GraphQlSpec {
    /// Look up a table spec by name.
    pub fn table(&self, name: &str) -> Option<&GraphQlTable> {
        self.tables.iter().find(|t| t.name == name)
    }
}

/// How to authenticate requests to the source. GraphQL APIs almost always use a
/// bearer token or a fixed API-key header, but basic auth is supported too.
#[derive(Debug, Clone, Serialize, Deserialize, Default)]
#[serde(tag = "type", rename_all = "snake_case")]
pub enum AuthSpec {
    /// No authentication (public API).
    #[default]
    None,
    /// `Authorization: Bearer <token>`.
    Bearer { token: String },
    /// HTTP Basic auth.
    Basic { username: String, password: String },
    /// A fixed header, e.g. `X-API-Key: <value>`.
    ApiKeyHeader { header: String, value: String },
}

/// One table: a stored GraphQL query that returns a list of records.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct GraphQlTable {
    /// The table name, e.g. `"countries"`.
    pub name: String,
    /// The GraphQL document to POST. It may declare variables the engine sets:
    /// the pagination variables (see [`Pagination::Relay`]) and any filter
    /// variables (see [`FilterVar`]).
    pub query: String,
    /// JSON pointer, *relative to the response's `data` object*, to the list or
    /// connection, e.g. `"/countries"` or `"/repository/issues"`.
    pub data_pointer: String,
    /// Whether `data_pointer` addresses a plain list or a Relay connection.
    #[serde(default)]
    pub shape: NodeShape,
    /// The columns to project from each node.
    pub columns: Vec<ColumnSpec>,
    /// How the query paginates.
    #[serde(default)]
    pub pagination: Pagination,
    /// Column → GraphQL-variable mappings enabling equality predicate pushdown.
    #[serde(default)]
    pub filters: Vec<FilterVar>,
}

/// One column: its name, where to read it from a node, and its type.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ColumnSpec {
    /// The SQL column name.
    pub name: String,
    /// Dotted path into a node object, e.g. `"name"` or `"continent.code"`.
    pub field: String,
    /// The column's type.
    pub data_type: DataType,
}

/// The shape of the value at a table's `data_pointer`.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize, Default)]
#[serde(rename_all = "snake_case")]
pub enum NodeShape {
    /// The pointer addresses a JSON array of node objects directly.
    #[default]
    List,
    /// The pointer addresses a Relay connection object: nodes live under
    /// `/edges/<i>/node` and paging info under `/pageInfo`.
    Connection,
}

/// How a query paginates.
#[derive(Debug, Clone, Serialize, Deserialize, Default)]
#[serde(tag = "style", rename_all = "snake_case")]
pub enum Pagination {
    /// Single request, no pagination.
    #[default]
    None,
    /// Relay cursor connections: set `first_var` to the page size and, after the
    /// first page, `after_var` to the previous page's `pageInfo.endCursor`.
    /// Continue while `pageInfo.hasNextPage` is true. Requires
    /// [`NodeShape::Connection`].
    Relay {
        first_var: String,
        after_var: String,
        page_size: usize,
    },
}

/// Maps a column to the GraphQL variable used to filter it (equality pushdown).
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct FilterVar {
    /// The column name as declared in [`ColumnSpec`].
    pub column: String,
    /// The GraphQL variable to set (without the `$`) when this column is
    /// filtered with `=`, e.g. `"code"` for `query($code: ID!) { ... }`.
    pub variable: String,
}

#[cfg(test)]
mod tests {
    use super::*;

    fn sample() -> GraphQlSpec {
        GraphQlSpec {
            name: "demo".into(),
            endpoint: "https://example.com/graphql".into(),
            auth: AuthSpec::Bearer { token: "t".into() },
            tables: vec![GraphQlTable {
                name: "issues".into(),
                query: "query($first:Int,$after:String){ issues(first:$first, after:$after){ edges{ node{ id title } } pageInfo{ hasNextPage endCursor } } }".into(),
                data_pointer: "/issues".into(),
                shape: NodeShape::Connection,
                columns: vec![ColumnSpec {
                    name: "id".into(),
                    field: "id".into(),
                    data_type: DataType::Text,
                }],
                pagination: Pagination::Relay {
                    first_var: "first".into(),
                    after_var: "after".into(),
                    page_size: 50,
                },
                filters: vec![FilterVar {
                    column: "state".into(),
                    variable: "state".into(),
                }],
            }],
        }
    }

    #[test]
    fn spec_round_trips_through_json() {
        let spec = sample();
        let json = serde_json::to_string(&spec).unwrap();
        let back: GraphQlSpec = serde_json::from_str(&json).unwrap();
        assert_eq!(back.name, "demo");
        assert_eq!(back.endpoint, "https://example.com/graphql");
        let t = back.table("issues").unwrap();
        assert_eq!(t.columns.len(), 1);
        assert_eq!(t.shape, NodeShape::Connection);
        assert!(back.table("missing").is_none());
        // Exercise Debug/Clone on the surviving value.
        assert!(!format!("{back:?}").is_empty());
        let _ = back.clone();
    }

    #[test]
    fn defaults_deserialize_when_omitted() {
        // auth, shape, pagination, filters all default.
        let json = r#"{
            "name": "d", "endpoint": "https://x/graphql",
            "tables": [{
                "name": "t", "query": "{ t { id } }", "data_pointer": "/t",
                "columns": [{"name":"id","field":"id","data_type":"Text"}]
            }]
        }"#;
        let spec: GraphQlSpec = serde_json::from_str(json).unwrap();
        assert!(matches!(spec.auth, AuthSpec::None));
        let t = &spec.tables[0];
        assert_eq!(t.shape, NodeShape::List);
        assert!(matches!(t.pagination, Pagination::None));
        assert!(t.filters.is_empty());
    }

    #[test]
    fn every_auth_variant_serializes() {
        for auth in [
            AuthSpec::None,
            AuthSpec::Bearer { token: "t".into() },
            AuthSpec::Basic {
                username: "u".into(),
                password: "p".into(),
            },
            AuthSpec::ApiKeyHeader {
                header: "X-API-Key".into(),
                value: "v".into(),
            },
        ] {
            let s = serde_json::to_string(&auth).unwrap();
            let _: AuthSpec = serde_json::from_str(&s).unwrap();
            assert!(!format!("{auth:?}").is_empty());
            let _ = auth.clone();
        }
    }

    #[test]
    fn every_shape_and_pagination_variant_serializes() {
        for shape in [NodeShape::List, NodeShape::Connection] {
            let s = serde_json::to_string(&shape).unwrap();
            let back: NodeShape = serde_json::from_str(&s).unwrap();
            assert_eq!(back, shape);
            assert!(!format!("{shape:?}").is_empty());
            let _ = shape; // Copy
        }
        for pg in [
            Pagination::None,
            Pagination::Relay {
                first_var: "first".into(),
                after_var: "after".into(),
                page_size: 100,
            },
        ] {
            let s = serde_json::to_string(&pg).unwrap();
            let _: Pagination = serde_json::from_str(&s).unwrap();
            assert!(!format!("{pg:?}").is_empty());
            let _ = pg.clone();
        }
    }

    #[test]
    fn column_and_filter_are_debuggable_and_cloneable() {
        let c = ColumnSpec {
            name: "id".into(),
            field: "sys.id".into(),
            data_type: DataType::Text,
        };
        assert!(!format!("{c:?}").is_empty());
        let _ = c.clone();
        let f = FilterVar {
            column: "code".into(),
            variable: "code".into(),
        };
        assert!(!format!("{f:?}").is_empty());
        let _ = f.clone();
    }
}
